spring:
  datasource:
    driver-class: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
